### ISSUE TITLE
Generate excel table with data from database

### ISSUE THREAD

**Issue by xyanid2015** [firegloves/MemPOI#3]
Is there a possibility to write  prepared statement not directly to  excel sheet, but create an excel table  before?

**Comment by firegloves** [comment]
Unfortunately at this time this feature is not supported. It could be an option for the next releases, but I have to check the impact on code base

**Comment by firegloves** [comment]
@xyanid2015 I'm developing excel table support. I'm planning to integrate also Pivot Table, so let me know if you need only the simple Excel table, please. In that case I could release 2 different updates, in order to fulfull your request in the meantime, otherwise I'll release directly at the end

**Comment by firegloves** [comment]
I've reviewed your request and decided to switch to a default behaviour for integer fields as you suggested.
