### ISSUE TITLE
Add custom cells

### ISSUE THREAD

**Issue by apoorva-sriv** [firegloves/MemPOI#55]
How can I add a title on the first row after using a row offset? I thought I could use `public Sheet getSheet()` from `MempoiSheet` and manipulate it with Apache POI, but the `private Sheet sheet` Javadoc says `DON'T POPULATE IT MANUALLY`.

**Comment by apoorva-sriv** [comment]
Just saw Lombok's `@Data` in the source file that generates the getters and setters, including `getSheet()`!

**Comment by firegloves** [comment]
@apoorva-sriv the automated addition of a title will be part of a future release.
Currently what you can do is:

- specify an offset
- request the generation of the `MempoiReport`
- get the `MempoiReport` from the resulting Future
- access the `file` property that returns the absolute path of the generated file
- open it with plain Apache POI API
- add manually the titles you require

Let me know if it is clear enough

**Comment by apoorva-sriv** [comment]
Got it. Thanks.

Small suggestion: can you add a link to the [website](https://firegloves.github.io/MemPOI/) or the animation as a GIF to the README? It's really cool and would make others even more interested in using the library!
