### ISSUE TITLE
Rearrange and Delete Columns Exported to Excel

### ISSUE THREAD

**Issue by apoorva-sriv** [firegloves/MemPOI#56]
If I cannot modify my SQL query, is there a way to rearrange and delete columns before exporting them to Excel?

**Comment by firegloves** [comment]
@apoorva-sriv currently there is no way to achieve your goal. But it is an interesting improvement that I will add to a future release. Thx for the idea

**Comment by firegloves** [comment]
As a workaround, you can obviously open the resulting file with plain Apache POI and remove the undesired columns.
I don't know how much complicated it is, especially if you want to rearrange their order instead of deleting them

**Comment by firegloves** [comment]
Functionality released with v1.10.0
