### ISSUE TITLE
`.withCellStyle()` not working with `XSSFWorkbook`

### ISSUE THREAD

**Issue by apoorva-sriv** [firegloves/MemPOI#65]
I created a cell style for right aligning some columns; however, Excel doesn't seem to consider it when I use `XSSFWorkbook`. It works when I use `SXSSFWorkbook` though.

**Comment by firegloves** [comment]
Hi @apoorva-sriv,
this is an old bug I had forgotten to fix. I've just published v1.9.1 which should fix the issue.

**Comment by apoorva-sriv** [comment]
Thank you for the quick fix! It's working now.
